name: Android CI Workflow

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8
          cache: 'gradle'

      - name: Run Lint checks and tests
        run: ./gradlew --no-daemon --parallel clean lintGmsDebug testGmsDebug lintFlossDebug testFlossDebug

      - name: Build debug artifacts
        shell: bash
        run: ./gradlew assembleDebug

      - uses: actions/upload-artifact@v3
        with:
          path: |
                app/build/outputs/apk/floss/debug/app-floss-debug.apk
                app/build/outputs/apk/gms/debug/app-gms-debug.apk
